# Generated by Django 4.1.1 on 2022-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_app', '0002_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izbran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izbran_title', models.CharField(max_length=40, verbose_name='Названия')),
                ('izbran_description', models.TextField(verbose_name='Описание')),
                ('izbran_send_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и Времия публикация')),
            ],
        ),
    ]
